steps:
  - wait

  - name: ":s3: Publish Edge Binaries"
    command: ".buildkite/steps/publish-to-s3.sh"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.0.0:
          login: true
          account-ids: "032379705303"
      - docker#v3.5.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          propagate-environment: true

  - name: ":redhat: Publish Edge RPM Package"
    command: ".buildkite/steps/publish-rpm-package.sh"
    env:
      CODENAME: "experimental"
      RPM_S3_BUCKET: "yum.buildkite.com"
    agents:
      queue: "deploy"
    plugins:
      - docker#v3.5.0:
          image: "buildkite/agent:3.45.0"
          entrypoint: bash
          propagate-environment: true
          volumes:
            - "/yum.buildkite.com"

  - name: ":debian: Publish Edge Debian Package"
    command: ".buildkite/steps/publish-debian-package.sh"
    env:
      CODENAME: "experimental"
      DEB_S3_BUCKET: "apt.buildkite.com/buildkite-agent"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.0.0:
          login: true
          account-ids: "032379705303"
      - docker#v3.5.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          propagate-environment: true
          tmpfs:
            - "/root/.gnupg"
    retry:
      automatic:
        - exit_status: 1
          limit: 3

  - name: ":docker: Publish Edge Docker Images"
    command: ".buildkite/steps/publish-docker-images.sh"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.0.0:
          login: true
          account-ids: "445615400570"
